[versions]
minecraft = "1.21.8"

[libraries]
fabricApi = "net.fabricmc.fabric-api:fabric-api:0.129.0+1.21.8"
fabricLoader = "net.fabricmc:fabric-loader:0.16.14"

[plugins]
fabricLoom = { id = "fabric-loom", version = "1.11-SNAPSHOT" }
